version: '3.9'

services:
  producer:
    build:
      context: ./producer
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - .env

  consumer:
    build:
      context: ./consumer
    ports:
      - "8001:8001"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]
    env_file:
      - .env